-- Seed sample ad campaigns for existing table structure
INSERT INTO ad_campaigns (
  title, 
  description, 
  ad_type, 
  placement_code,
  status, 
  budget_total, 
  spent_amount, 
  start_date, 
  end_date, 
  landing_page, 
  link,
  target_audience, 
  advertiser_name, 
  advertiser_email,
  impressions,
  clicks,
  conversions,
  primary_image_url,
  cta_text,
  cta_link
) VALUES
  (
    'Premium Real Estate - Kigali Heights',
    'Luxury apartments in the heart of Kigali with amazing city views',
    'banner',
    'homepage_leaderboard',
    'active',
    15000,
    8500,
    '2024-01-15',
    '2024-02-15',
    '/listings/houses',
    '/listings/houses',
    'Property buyers, 25-45 age, high income',
    'Kigali Heights Realty',
    'info@kigaliheights.rw',
    15420,
    342,
    12,
    'https://res.cloudinary.com/dp7yzc36n/image/upload/v1770465611/ikazeproperty/kigali-heights-banner.jpg',
    'View Properties',
    '/listings/houses'
  ),
  (
    'Car Insurance - Rwanda Insurance',
    'Protect your vehicle with comprehensive coverage',
    'sidebar',
    'homepage_sidebar',
    'active',
    20000,
    12000,
    '2024-01-10',
    '2024-02-10',
    '#',
    '#',
    'Car owners, 25-60 age',
    'Rwanda Insurance Ltd',
    'contact@rwandainsurance.rw',
    8900,
    156,
    8,
    'https://res.cloudinary.com/dp7yzc36n/image/upload/v1770465611/ikazeproperty/car-insurance-sidebar.jpg',
    'Get Quote',
    '#'
  ),
  (
    'Property Management Services',
    'Professional property management for landlords',
    'banner',
    'category_top',
    'active',
    10000,
    4500,
    '2024-01-12',
    '2024-02-12',
    '#',
    '#',
    'Property investors, landlords',
    'Property Management Co',
    'services@propertymanagement.rw',
    6700,
    89,
    5,
    'https://res.cloudinary.com/dp7yzc36n/image/upload/v1770465611/ikazeproperty/property-management-banner.jpg',
    'Learn More',
    '#'
  ),
  (
    'Featured: Modern Villa in Nyarutarama',
    '5 bedrooms, swimming pool, garden, prime location',
    'featured',
    'featured_carousel',
    'active',
    25000,
    15000,
    '2024-01-08',
    '2024-02-08',
    '/listings/houses/1',
    '/listings/houses/1',
    'Luxury home buyers, 35-55 age',
    'Premium Properties',
    'premium@properties.rw',
    12300,
    278,
    15,
    'https://res.cloudinary.com/dp7yzc36n/image/upload/v1770465611/ikazeproperty/modern-villa-featured.jpg',
    'View Details',
    '/listings/houses/1'
  ),
  (
    'Home Loan Services - Bank of Kigali',
    'Get pre-approved for your dream home',
    'sidebar',
    'listing_sidebar',
    'pending',
    18000,
    0,
    '2024-01-20',
    '2024-02-20',
    '#',
    '#',
    'Home buyers, 25-50 age',
    'Bank of Kigali',
    'loans@bankofkigali.rw',
    0,
    0,
    0,
    'https://res.cloudinary.com/dp7yzc36n/image/upload/v1770465611/ikazeproperty/bank-kigali-sidebar.jpg',
    'Apply Now',
    '#'
  )
ON CONFLICT (id) DO NOTHING;
